### ISSUE TITLE
Question - is it required to add reflection-config entries for Firebase notification objects?

### ISSUE THREAD

**Issue by ygyg70** [quarkiverse/quarkus-google-cloud-services#417] opened 2023-04-19 22:00 UTC
Firebase notifications with native image didn't otherwise work.
Ended up adding entries for the following classes to reflection-config.json:
Message.class
Notification.class,
AndroidConfig.class,
AndroidNotification.class,
AndroidFcmOptions.class,
WebpushConfig.class,
WebpushFcmOptions.class,
WebpushNotification.class,
ApnsConfig.class,
ApnsFcmOptions.class,
ApsAlert.class,
FcmOptions.class,
MessagingServiceResponse.class

**Comment by loicmathieu** [comment] 2023-04-20 07:17
@ygyg70 I don't understand the question.

Is there missing native image configuration for one of the extension in this repository ?

By the way, Google tries to manage native image configuration in each library, reflective access should be handle on their side so you can open an issue upstream so it will be available for everyone and not just Quarkus users

**Comment by ygyg70** [comment] 2023-04-21 08:11
https://github.com/firebase/firebase-admin-java/issues/800

**Comment by loicmathieu** [comment] 2023-04-21 10:27
Great, I'll close it as dependabot will create an update PR when the issue is fixed upstream.
Please re-open it if something has to be done at our side except a dependency upgrade.

**Closed by loicmathieu** 2023-04-21 10:27 UTC
Labels: upsteam
